spring:
  application:
    name: dpCalculator
eureka:
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
application:
  wait-in-microseconds-between-reads: 50
  input-queue: D:/queues
  output-queue: D:/engine-queue
  messages-queue-size: 1000000
  engine:
    name: engine
    connections-attempts: 2